# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
minimal_mistakes_skin    : "air"

# Site Settings
locale                   : "en-US"
title                    : "LGKZanini"
title_separator          : "-"
subtitle                 : "A website about my work and research"
name                     : "Luiz Zanini"
description              : "A website about my work and research."
url                      : "https://lgkzanini.github.io"
baseurl                  : "" 
repository               : "LGKZanini/LGKZanini.github.io"
teaser                   : "/assets/images/personal.jpg" 
masthead_title           : "" 
words_per_minute         : 200

comments:
  provider               : false

atom_feed:
  path                   : feed.xml

# Social Sharing
twitter:
  username               : luizzanini

# Social Profiles
social:
  type                   : Person
  name                   : Luiz Zanini
  links: 
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/luiz-guilherme-zanini-8555671a4/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LGKZanini"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=AQ6wte8AAAAJ&hl=pt-BR&authuser=1"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/my-orcid?orcid=0000-0002-8344-3178"

# Analytics
analytics:
  provider               : false 

# Site Author
author:
  name             : "Luiz Guilherme Kasputis Zanini"
  avatar           : "/assets/images/personal.jpg"
  bio              : "Researcher in Engineering focusing on Computer Vision - LAB [LIVIA](https://liviamtl.ca/) <br/> luiz.kasputis-zanini.1@ens.etsmtl.ca"
  location         : "Montreal, Canada"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/luiz-guilherme-zanini-8555671a4/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LGKZanini"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=AQ6wte8AAAAJ&hl=pt-BR&authuser=1"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/my-orcid?orcid=0000-0002-8344-3178"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/luiz-guilherme-zanini-8555671a4/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LGKZanini"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=AQ6wte8AAAAJ&hl=pt-BR&authuser=1"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/my-orcid?orcid=0000-0002-8344-3178"

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs 
  - /test 

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
timezone: "America/Montreal"

# Plugins 
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression 
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: 
      share: true
      related: true